# Generated by Django 4.2.1 on 2023-06-06 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_razao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('dt_nasc_abertura', models.DateField()),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibilidade', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('chave', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('fk_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_destinatario', to=settings.AUTH_USER_MODEL)),
                ('fk_remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_remetente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_parcela', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('validade', models.DateField()),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
